server.port=8083
spring.application.name=api-gateway-service

#microservices routing configuration
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:9006/
spring.cloud.gateway.routes[0].predicates[0].name=Path
spring.cloud.gateway.routes[0].predicates[0].args[pattern]=/api/v1/users/**
spring.cloud.gateway.routes[0].filters=AuthenticationFilter

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=http://localhost:9001/
spring.cloud.gateway.routes[1].predicates[0].name=Path
spring.cloud.gateway.routes[1].predicates[0].args[pattern]=/api/v1/products/**
spring.cloud.gateway.routes[1].filters=AuthenticationFilter

spring.cloud.gateway.routes[2].id=price-service
spring.cloud.gateway.routes[2].uri=http://localhost:9002/
spring.cloud.gateway.routes[2].predicates[0].name=Path
spring.cloud.gateway.routes[2].predicates[0].args[pattern]=/api/v1/prices/**
spring.cloud.gateway.routes[2].filters=AuthenticationFilter

spring.cloud.gateway.routes[3].id=cart-service
spring.cloud.gateway.routes[3].uri=http://localhost:9003/
spring.cloud.gateway.routes[3].predicates[0].name=Path
spring.cloud.gateway.routes[3].predicates[0].args[pattern]=/api/v1/carts/**
spring.cloud.gateway.routes[3].filters=AuthenticationFilter

spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=http://localhost:9004/
spring.cloud.gateway.routes[4].predicates[0].name=Path
spring.cloud.gateway.routes[4].predicates[0].args[pattern]=/api/v1/orders/**
spring.cloud.gateway.routes[4].filters=AuthenticationFilter

spring.cloud.gateway.routes[5].id=auth-service
spring.cloud.gateway.routes[5].uri=http://localhost:9006/
spring.cloud.gateway.routes[5].predicates[0].name=Path
spring.cloud.gateway.routes[5].predicates[0].args[pattern]=/api/v1/auth/**
spring.cloud.gateway.routes[5].filters=AuthenticationFilter

#zipkin tracer configuration
management.tracing.sampling.probability=1.0

#eureka server configuration
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka